echo "Use: "
echo "  -f to specify a new filename (default value = \"final-recipes.json\")"
echo "  -d to enter a directory use a different directory name for indexes (default value = \"recipes\")"
echo "  -t set 'True' to test the timing of indexer (default value = \"False\")"
echo "  -q if you want to run your query on specific field either \"title\", \"ingredients\", \"directions\""
echo "  -c you can set this value to change the amount of results you want to see"
echo "  -m sample size, indicates how many intervals will be tested"
echo " "
echo "To quit from the search engine type: 'quit()'"

